insert into services(duration,name,agency_id) values(15,"amenda circulatie",5);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",5);
insert into services(duration,name,agency_id) values(10,"amenzi publice",5);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",10);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",10);
insert into services(duration,name,agency_id) values(10,"amenzi publice",10);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",15);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",15);
insert into services(duration,name,agency_id) values(10,"amenzi publice",15);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",20);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",20);
insert into services(duration,name,agency_id) values(10,"amenzi publice",20);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",25);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",25);
insert into services(duration,name,agency_id) values(10,"amenzi publice",25);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",30);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",30);
insert into services(duration,name,agency_id) values(10,"amenzi publice",30);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",35);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",35);
insert into services(duration,name,agency_id) values(10,"amenzi publice",35);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",40);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",40);
insert into services(duration,name,agency_id) values(10,"amenzi publice",40);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",45);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",45);
insert into services(duration,name,agency_id) values(10,"amenzi publice",45);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",50);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",50);
insert into services(duration,name,agency_id) values(10,"amenzi publice",50);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",55);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",55);
insert into services(duration,name,agency_id) values(10,"amenzi publice",55);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",60);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",60);
insert into services(duration,name,agency_id) values(10,"amenzi publice",60);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",65);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",65);
insert into services(duration,name,agency_id) values(10,"amenzi publice",65);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",70);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",70);
insert into services(duration,name,agency_id) values(10,"amenzi publice",70);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",75);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",75);
insert into services(duration,name,agency_id) values(10,"amenzi publice",75);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",80);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",80);
insert into services(duration,name,agency_id) values(10,"amenzi publice",80);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",85);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",85);
insert into services(duration,name,agency_id) values(10,"amenzi publice",85);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",90);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",90);
insert into services(duration,name,agency_id) values(10,"amenzi publice",90);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",95);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",95);
insert into services(duration,name,agency_id) values(10,"amenzi publice",95);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",100);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",100);
insert into services(duration,name,agency_id) values(10,"amenzi publice",100);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",105);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",105);
insert into services(duration,name,agency_id) values(10,"amenzi publice",105);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",110);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",110);
insert into services(duration,name,agency_id) values(10,"amenzi publice",110);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",115);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",115);
insert into services(duration,name,agency_id) values(10,"amenzi publice",115);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",120);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",120);
insert into services(duration,name,agency_id) values(10,"amenzi publice",120);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",125);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",125);
insert into services(duration,name,agency_id) values(10,"amenzi publice",125);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",130);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",130);
insert into services(duration,name,agency_id) values(10,"amenzi publice",130);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",135);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",135);
insert into services(duration,name,agency_id) values(10,"amenzi publice",135);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",140);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",140);
insert into services(duration,name,agency_id) values(10,"amenzi publice",140);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",145);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",145);
insert into services(duration,name,agency_id) values(10,"amenzi publice",145);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",150);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",150);
insert into services(duration,name,agency_id) values(10,"amenzi publice",150);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",155);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",155);
insert into services(duration,name,agency_id) values(10,"amenzi publice",155);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",160);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",160);
insert into services(duration,name,agency_id) values(10,"amenzi publice",160);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",165);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",165);
insert into services(duration,name,agency_id) values(10,"amenzi publice",165);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",170);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",170);
insert into services(duration,name,agency_id) values(10,"amenzi publice",170);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",175);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",175);
insert into services(duration,name,agency_id) values(10,"amenzi publice",175);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",180);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",180);
insert into services(duration,name,agency_id) values(10,"amenzi publice",180);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",185);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",185);
insert into services(duration,name,agency_id) values(10,"amenzi publice",185);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",190);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",190);
insert into services(duration,name,agency_id) values(10,"amenzi publice",190);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",195);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",195);
insert into services(duration,name,agency_id) values(10,"amenzi publice",195);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",200);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",200);
insert into services(duration,name,agency_id) values(10,"amenzi publice",200);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",205);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",205);
insert into services(duration,name,agency_id) values(10,"amenzi publice",205);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",210);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",210);
insert into services(duration,name,agency_id) values(10,"amenzi publice",210);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",215);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",215);
insert into services(duration,name,agency_id) values(10,"amenzi publice",215);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",220);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",220);
insert into services(duration,name,agency_id) values(10,"amenzi publice",220);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",225);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",225);
insert into services(duration,name,agency_id) values(10,"amenzi publice",225);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",230);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",230);
insert into services(duration,name,agency_id) values(10,"amenzi publice",230);
insert into services(duration,name,agency_id) values(15,"amenda circulatie",235);
insert into services(duration,name,agency_id) values(5,"amenda rovineta",235);
insert into services(duration,name,agency_id) values(10,"amenzi publice",235);
insert into services(duration,name,agency_id) values(30,"Formular 010",2);
insert into services(duration,name,agency_id) values(60,"Formular 014",2);
insert into services(duration,name,agency_id) values(5,"Formular 015",2);
insert into services(duration,name,agency_id) values(10,"Formular 093",2);
insert into services(duration,name,agency_id) values(30,"Formular 010",7);
insert into services(duration,name,agency_id) values(60,"Formular 014",7);
insert into services(duration,name,agency_id) values(5,"Formular 015",7);
insert into services(duration,name,agency_id) values(10,"Formular 093",7);
insert into services(duration,name,agency_id) values(30,"Formular 010",12);
insert into services(duration,name,agency_id) values(60,"Formular 014",12);
insert into services(duration,name,agency_id) values(5,"Formular 015",12);
insert into services(duration,name,agency_id) values(10,"Formular 093",12);
insert into services(duration,name,agency_id) values(30,"Formular 010",17);
insert into services(duration,name,agency_id) values(60,"Formular 014",17);
insert into services(duration,name,agency_id) values(5,"Formular 015",17);
insert into services(duration,name,agency_id) values(10,"Formular 093",17);
insert into services(duration,name,agency_id) values(30,"Formular 010",22);
insert into services(duration,name,agency_id) values(60,"Formular 014",22);
insert into services(duration,name,agency_id) values(5,"Formular 015",22);
insert into services(duration,name,agency_id) values(10,"Formular 093",22);
insert into services(duration,name,agency_id) values(30,"Formular 010",27);
insert into services(duration,name,agency_id) values(60,"Formular 014",27);
insert into services(duration,name,agency_id) values(5,"Formular 015",27);
insert into services(duration,name,agency_id) values(10,"Formular 093",27);
insert into services(duration,name,agency_id) values(30,"Formular 010",32);
insert into services(duration,name,agency_id) values(60,"Formular 014",32);
insert into services(duration,name,agency_id) values(5,"Formular 015",32);
insert into services(duration,name,agency_id) values(10,"Formular 093",32);
insert into services(duration,name,agency_id) values(30,"Formular 010",37);
insert into services(duration,name,agency_id) values(60,"Formular 014",37);
insert into services(duration,name,agency_id) values(5,"Formular 015",37);
insert into services(duration,name,agency_id) values(10,"Formular 093",37);
insert into services(duration,name,agency_id) values(30,"Formular 010",42);
insert into services(duration,name,agency_id) values(60,"Formular 014",42);
insert into services(duration,name,agency_id) values(5,"Formular 015",42);
insert into services(duration,name,agency_id) values(10,"Formular 093",42);
insert into services(duration,name,agency_id) values(30,"Formular 010",47);
insert into services(duration,name,agency_id) values(60,"Formular 014",47);
insert into services(duration,name,agency_id) values(5,"Formular 015",47);
insert into services(duration,name,agency_id) values(10,"Formular 093",47);
insert into services(duration,name,agency_id) values(30,"Formular 010",52);
insert into services(duration,name,agency_id) values(60,"Formular 014",52);
insert into services(duration,name,agency_id) values(5,"Formular 015",52);
insert into services(duration,name,agency_id) values(10,"Formular 093",52);
insert into services(duration,name,agency_id) values(30,"Formular 010",57);
insert into services(duration,name,agency_id) values(60,"Formular 014",57);
insert into services(duration,name,agency_id) values(5,"Formular 015",57);
insert into services(duration,name,agency_id) values(10,"Formular 093",57);
insert into services(duration,name,agency_id) values(30,"Formular 010",62);
insert into services(duration,name,agency_id) values(60,"Formular 014",62);
insert into services(duration,name,agency_id) values(5,"Formular 015",62);
insert into services(duration,name,agency_id) values(10,"Formular 093",62);
insert into services(duration,name,agency_id) values(30,"Formular 010",67);
insert into services(duration,name,agency_id) values(60,"Formular 014",67);
insert into services(duration,name,agency_id) values(5,"Formular 015",67);
insert into services(duration,name,agency_id) values(10,"Formular 093",67);
insert into services(duration,name,agency_id) values(30,"Formular 010",72);
insert into services(duration,name,agency_id) values(60,"Formular 014",72);
insert into services(duration,name,agency_id) values(5,"Formular 015",72);
insert into services(duration,name,agency_id) values(10,"Formular 093",72);
insert into services(duration,name,agency_id) values(30,"Formular 010",77);
insert into services(duration,name,agency_id) values(60,"Formular 014",77);
insert into services(duration,name,agency_id) values(5,"Formular 015",77);
insert into services(duration,name,agency_id) values(10,"Formular 093",77);
insert into services(duration,name,agency_id) values(30,"Formular 010",82);
insert into services(duration,name,agency_id) values(60,"Formular 014",82);
insert into services(duration,name,agency_id) values(5,"Formular 015",82);
insert into services(duration,name,agency_id) values(10,"Formular 093",82);
insert into services(duration,name,agency_id) values(30,"Formular 010",87);
insert into services(duration,name,agency_id) values(60,"Formular 014",87);
insert into services(duration,name,agency_id) values(5,"Formular 015",87);
insert into services(duration,name,agency_id) values(10,"Formular 093",87);
insert into services(duration,name,agency_id) values(30,"Formular 010",92);
insert into services(duration,name,agency_id) values(60,"Formular 014",92);
insert into services(duration,name,agency_id) values(5,"Formular 015",92);
insert into services(duration,name,agency_id) values(10,"Formular 093",92);
insert into services(duration,name,agency_id) values(30,"Formular 010",97);
insert into services(duration,name,agency_id) values(60,"Formular 014",97);
insert into services(duration,name,agency_id) values(5,"Formular 015",97);
insert into services(duration,name,agency_id) values(10,"Formular 093",97);
insert into services(duration,name,agency_id) values(30,"Formular 010",102);
insert into services(duration,name,agency_id) values(60,"Formular 014",102);
insert into services(duration,name,agency_id) values(5,"Formular 015",102);
insert into services(duration,name,agency_id) values(10,"Formular 093",102);
insert into services(duration,name,agency_id) values(30,"Formular 010",107);
insert into services(duration,name,agency_id) values(60,"Formular 014",107);
insert into services(duration,name,agency_id) values(5,"Formular 015",107);
insert into services(duration,name,agency_id) values(10,"Formular 093",107);
insert into services(duration,name,agency_id) values(30,"Formular 010",112);
insert into services(duration,name,agency_id) values(60,"Formular 014",112);
insert into services(duration,name,agency_id) values(5,"Formular 015",112);
insert into services(duration,name,agency_id) values(10,"Formular 093",112);
insert into services(duration,name,agency_id) values(30,"Formular 010",117);
insert into services(duration,name,agency_id) values(60,"Formular 014",117);
insert into services(duration,name,agency_id) values(5,"Formular 015",117);
insert into services(duration,name,agency_id) values(10,"Formular 093",117);
insert into services(duration,name,agency_id) values(30,"Formular 010",122);
insert into services(duration,name,agency_id) values(60,"Formular 014",122);
insert into services(duration,name,agency_id) values(5,"Formular 015",122);
insert into services(duration,name,agency_id) values(10,"Formular 093",122);
insert into services(duration,name,agency_id) values(30,"Formular 010",127);
insert into services(duration,name,agency_id) values(60,"Formular 014",127);
insert into services(duration,name,agency_id) values(5,"Formular 015",127);
insert into services(duration,name,agency_id) values(10,"Formular 093",127);
insert into services(duration,name,agency_id) values(30,"Formular 010",132);
insert into services(duration,name,agency_id) values(60,"Formular 014",132);
insert into services(duration,name,agency_id) values(5,"Formular 015",132);
insert into services(duration,name,agency_id) values(10,"Formular 093",132);
insert into services(duration,name,agency_id) values(30,"Formular 010",137);
insert into services(duration,name,agency_id) values(60,"Formular 014",137);
insert into services(duration,name,agency_id) values(5,"Formular 015",137);
insert into services(duration,name,agency_id) values(10,"Formular 093",137);
insert into services(duration,name,agency_id) values(30,"Formular 010",142);
insert into services(duration,name,agency_id) values(60,"Formular 014",142);
insert into services(duration,name,agency_id) values(5,"Formular 015",142);
insert into services(duration,name,agency_id) values(10,"Formular 093",142);
insert into services(duration,name,agency_id) values(30,"Formular 010",147);
insert into services(duration,name,agency_id) values(60,"Formular 014",147);
insert into services(duration,name,agency_id) values(5,"Formular 015",147);
insert into services(duration,name,agency_id) values(10,"Formular 093",147);
insert into services(duration,name,agency_id) values(30,"Formular 010",152);
insert into services(duration,name,agency_id) values(60,"Formular 014",152);
insert into services(duration,name,agency_id) values(5,"Formular 015",152);
insert into services(duration,name,agency_id) values(10,"Formular 093",152);
insert into services(duration,name,agency_id) values(30,"Formular 010",157);
insert into services(duration,name,agency_id) values(60,"Formular 014",157);
insert into services(duration,name,agency_id) values(5,"Formular 015",157);
insert into services(duration,name,agency_id) values(10,"Formular 093",157);
insert into services(duration,name,agency_id) values(30,"Formular 010",162);
insert into services(duration,name,agency_id) values(60,"Formular 014",162);
insert into services(duration,name,agency_id) values(5,"Formular 015",162);
insert into services(duration,name,agency_id) values(10,"Formular 093",162);
insert into services(duration,name,agency_id) values(30,"Formular 010",167);
insert into services(duration,name,agency_id) values(60,"Formular 014",167);
insert into services(duration,name,agency_id) values(5,"Formular 015",167);
insert into services(duration,name,agency_id) values(10,"Formular 093",167);
insert into services(duration,name,agency_id) values(30,"Formular 010",172);
insert into services(duration,name,agency_id) values(60,"Formular 014",172);
insert into services(duration,name,agency_id) values(5,"Formular 015",172);
insert into services(duration,name,agency_id) values(10,"Formular 093",172);
insert into services(duration,name,agency_id) values(30,"Formular 010",177);
insert into services(duration,name,agency_id) values(60,"Formular 014",177);
insert into services(duration,name,agency_id) values(5,"Formular 015",177);
insert into services(duration,name,agency_id) values(10,"Formular 093",177);
insert into services(duration,name,agency_id) values(30,"Formular 010",182);
insert into services(duration,name,agency_id) values(60,"Formular 014",182);
insert into services(duration,name,agency_id) values(5,"Formular 015",182);
insert into services(duration,name,agency_id) values(10,"Formular 093",182);
insert into services(duration,name,agency_id) values(30,"Formular 010",187);
insert into services(duration,name,agency_id) values(60,"Formular 014",187);
insert into services(duration,name,agency_id) values(5,"Formular 015",187);
insert into services(duration,name,agency_id) values(10,"Formular 093",187);
insert into services(duration,name,agency_id) values(30,"Formular 010",192);
insert into services(duration,name,agency_id) values(60,"Formular 014",192);
insert into services(duration,name,agency_id) values(5,"Formular 015",192);
insert into services(duration,name,agency_id) values(10,"Formular 093",192);
insert into services(duration,name,agency_id) values(30,"Formular 010",197);
insert into services(duration,name,agency_id) values(60,"Formular 014",197);
insert into services(duration,name,agency_id) values(5,"Formular 015",197);
insert into services(duration,name,agency_id) values(10,"Formular 093",197);
insert into services(duration,name,agency_id) values(30,"Formular 010",202);
insert into services(duration,name,agency_id) values(60,"Formular 014",202);
insert into services(duration,name,agency_id) values(5,"Formular 015",202);
insert into services(duration,name,agency_id) values(10,"Formular 093",202);
insert into services(duration,name,agency_id) values(30,"Formular 010",207);
insert into services(duration,name,agency_id) values(60,"Formular 014",207);
insert into services(duration,name,agency_id) values(5,"Formular 015",207);
insert into services(duration,name,agency_id) values(10,"Formular 093",207);
insert into services(duration,name,agency_id) values(30,"Formular 010",212);
insert into services(duration,name,agency_id) values(60,"Formular 014",212);
insert into services(duration,name,agency_id) values(5,"Formular 015",212);
insert into services(duration,name,agency_id) values(10,"Formular 093",212);
insert into services(duration,name,agency_id) values(30,"Formular 010",217);
insert into services(duration,name,agency_id) values(60,"Formular 014",217);
insert into services(duration,name,agency_id) values(5,"Formular 015",217);
insert into services(duration,name,agency_id) values(10,"Formular 093",217);
insert into services(duration,name,agency_id) values(30,"Formular 010",222);
insert into services(duration,name,agency_id) values(60,"Formular 014",222);
insert into services(duration,name,agency_id) values(5,"Formular 015",222);
insert into services(duration,name,agency_id) values(10,"Formular 093",222);
insert into services(duration,name,agency_id) values(30,"Formular 010",227);
insert into services(duration,name,agency_id) values(60,"Formular 014",227);
insert into services(duration,name,agency_id) values(5,"Formular 015",227);
insert into services(duration,name,agency_id) values(10,"Formular 093",227);
insert into services(duration,name,agency_id) values(30,"Formular 010",232);
insert into services(duration,name,agency_id) values(60,"Formular 014",232);
insert into services(duration,name,agency_id) values(5,"Formular 015",232);
insert into services(duration,name,agency_id) values(10,"Formular 093",232);
insert into services(duration,name,agency_id) values(5,"impozit casa",3);
insert into services(duration,name,agency_id) values(10,"impozit masina",3);
insert into services(duration,name,agency_id) values(5,"impozit casa",8);
insert into services(duration,name,agency_id) values(10,"impozit masina",8);
insert into services(duration,name,agency_id) values(5,"impozit casa",13);
insert into services(duration,name,agency_id) values(10,"impozit masina",13);
insert into services(duration,name,agency_id) values(5,"impozit casa",18);
insert into services(duration,name,agency_id) values(10,"impozit masina",18);
insert into services(duration,name,agency_id) values(5,"impozit casa",23);
insert into services(duration,name,agency_id) values(10,"impozit masina",23);
insert into services(duration,name,agency_id) values(5,"impozit casa",28);
insert into services(duration,name,agency_id) values(10,"impozit masina",28);
insert into services(duration,name,agency_id) values(5,"impozit casa",33);
insert into services(duration,name,agency_id) values(10,"impozit masina",33);
insert into services(duration,name,agency_id) values(5,"impozit casa",38);
insert into services(duration,name,agency_id) values(10,"impozit masina",38);
insert into services(duration,name,agency_id) values(5,"impozit casa",43);
insert into services(duration,name,agency_id) values(10,"impozit masina",43);
insert into services(duration,name,agency_id) values(5,"impozit casa",48);
insert into services(duration,name,agency_id) values(10,"impozit masina",48);
insert into services(duration,name,agency_id) values(5,"impozit casa",53);
insert into services(duration,name,agency_id) values(10,"impozit masina",53);
insert into services(duration,name,agency_id) values(5,"impozit casa",58);
insert into services(duration,name,agency_id) values(10,"impozit masina",58);
insert into services(duration,name,agency_id) values(5,"impozit casa",63);
insert into services(duration,name,agency_id) values(10,"impozit masina",63);
insert into services(duration,name,agency_id) values(5,"impozit casa",68);
insert into services(duration,name,agency_id) values(10,"impozit masina",68);
insert into services(duration,name,agency_id) values(5,"impozit casa",73);
insert into services(duration,name,agency_id) values(10,"impozit masina",73);
insert into services(duration,name,agency_id) values(5,"impozit casa",78);
insert into services(duration,name,agency_id) values(10,"impozit masina",78);
insert into services(duration,name,agency_id) values(5,"impozit casa",83);
insert into services(duration,name,agency_id) values(10,"impozit masina",83);
insert into services(duration,name,agency_id) values(5,"impozit casa",88);
insert into services(duration,name,agency_id) values(10,"impozit masina",88);
insert into services(duration,name,agency_id) values(5,"impozit casa",93);
insert into services(duration,name,agency_id) values(10,"impozit masina",93);
insert into services(duration,name,agency_id) values(5,"impozit casa",98);
insert into services(duration,name,agency_id) values(10,"impozit masina",98);
insert into services(duration,name,agency_id) values(5,"impozit casa",103);
insert into services(duration,name,agency_id) values(10,"impozit masina",103);
insert into services(duration,name,agency_id) values(5,"impozit casa",108);
insert into services(duration,name,agency_id) values(10,"impozit masina",108);
insert into services(duration,name,agency_id) values(5,"impozit casa",113);
insert into services(duration,name,agency_id) values(10,"impozit masina",113);
insert into services(duration,name,agency_id) values(5,"impozit casa",118);
insert into services(duration,name,agency_id) values(10,"impozit masina",118);
insert into services(duration,name,agency_id) values(5,"impozit casa",123);
insert into services(duration,name,agency_id) values(10,"impozit masina",123);
insert into services(duration,name,agency_id) values(5,"impozit casa",128);
insert into services(duration,name,agency_id) values(10,"impozit masina",128);
insert into services(duration,name,agency_id) values(5,"impozit casa",133);
insert into services(duration,name,agency_id) values(10,"impozit masina",133);
insert into services(duration,name,agency_id) values(5,"impozit casa",138);
insert into services(duration,name,agency_id) values(10,"impozit masina",138);
insert into services(duration,name,agency_id) values(5,"impozit casa",143);
insert into services(duration,name,agency_id) values(10,"impozit masina",143);
insert into services(duration,name,agency_id) values(5,"impozit casa",148);
insert into services(duration,name,agency_id) values(10,"impozit masina",148);
insert into services(duration,name,agency_id) values(5,"impozit casa",153);
insert into services(duration,name,agency_id) values(10,"impozit masina",153);
insert into services(duration,name,agency_id) values(5,"impozit casa",158);
insert into services(duration,name,agency_id) values(10,"impozit masina",158);
insert into services(duration,name,agency_id) values(5,"impozit casa",163);
insert into services(duration,name,agency_id) values(10,"impozit masina",163);
insert into services(duration,name,agency_id) values(5,"impozit casa",168);
insert into services(duration,name,agency_id) values(10,"impozit masina",168);
insert into services(duration,name,agency_id) values(5,"impozit casa",173);
insert into services(duration,name,agency_id) values(10,"impozit masina",173);
insert into services(duration,name,agency_id) values(5,"impozit casa",178);
insert into services(duration,name,agency_id) values(10,"impozit masina",178);
insert into services(duration,name,agency_id) values(5,"impozit casa",183);
insert into services(duration,name,agency_id) values(10,"impozit masina",183);
insert into services(duration,name,agency_id) values(5,"impozit casa",188);
insert into services(duration,name,agency_id) values(10,"impozit masina",188);
insert into services(duration,name,agency_id) values(5,"impozit casa",193);
insert into services(duration,name,agency_id) values(10,"impozit masina",193);
insert into services(duration,name,agency_id) values(5,"impozit casa",198);
insert into services(duration,name,agency_id) values(10,"impozit masina",198);
insert into services(duration,name,agency_id) values(5,"impozit casa",203);
insert into services(duration,name,agency_id) values(10,"impozit masina",203);
insert into services(duration,name,agency_id) values(5,"impozit casa",208);
insert into services(duration,name,agency_id) values(10,"impozit masina",208);
insert into services(duration,name,agency_id) values(5,"impozit casa",213);
insert into services(duration,name,agency_id) values(10,"impozit masina",213);
insert into services(duration,name,agency_id) values(5,"impozit casa",218);
insert into services(duration,name,agency_id) values(10,"impozit masina",218);
insert into services(duration,name,agency_id) values(5,"impozit casa",223);
insert into services(duration,name,agency_id) values(10,"impozit masina",223);
insert into services(duration,name,agency_id) values(5,"impozit casa",228);
insert into services(duration,name,agency_id) values(10,"impozit masina",228);
insert into services(duration,name,agency_id) values(5,"impozit casa",233);
insert into services(duration,name,agency_id) values(10,"impozit masina",233);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",1);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",1);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",1);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",1);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",1);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",1);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",1);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",6);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",6);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",6);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",6);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",6);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",6);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",6);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",11);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",11);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",11);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",11);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",11);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",11);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",11);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",16);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",16);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",16);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",16);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",16);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",16);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",16);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",21);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",21);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",21);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",21);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",21);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",21);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",21);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",26);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",26);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",26);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",26);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",26);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",26);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",26);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",31);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",31);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",31);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",31);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",31);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",31);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",31);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",36);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",36);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",36);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",36);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",36);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",36);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",36);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",41);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",41);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",41);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",41);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",41);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",41);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",41);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",46);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",46);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",46);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",46);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",46);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",46);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",46);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",51);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",51);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",51);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",51);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",51);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",51);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",51);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",56);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",56);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",56);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",56);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",56);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",56);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",56);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",61);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",61);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",61);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",61);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",61);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",61);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",61);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",66);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",66);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",66);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",66);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",66);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",66);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",66);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",71);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",71);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",71);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",71);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",71);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",71);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",71);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",76);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",76);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",76);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",76);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",76);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",76);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",76);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",81);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",81);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",81);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",81);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",81);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",81);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",81);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",86);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",86);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",86);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",86);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",86);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",86);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",86);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",91);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",91);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",91);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",91);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",91);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",91);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",91);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",96);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",96);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",96);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",96);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",96);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",96);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",96);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",101);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",101);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",101);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",101);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",101);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",101);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",101);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",106);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",106);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",106);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",106);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",106);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",106);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",106);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",111);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",111);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",111);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",111);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",111);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",111);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",111);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",116);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",116);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",116);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",116);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",116);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",116);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",116);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",121);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",121);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",121);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",121);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",121);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",121);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",121);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",126);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",126);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",126);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",126);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",126);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",126);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",126);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",131);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",131);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",131);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",131);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",131);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",131);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",131);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",136);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",136);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",136);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",136);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",136);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",136);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",136);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",141);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",141);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",141);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",141);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",141);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",141);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",141);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",146);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",146);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",146);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",146);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",146);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",146);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",146);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",151);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",151);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",151);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",151);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",151);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",151);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",151);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",156);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",156);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",156);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",156);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",156);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",156);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",156);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",161);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",161);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",161);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",161);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",161);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",161);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",161);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",166);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",166);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",166);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",166);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",166);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",166);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",166);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",171);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",171);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",171);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",171);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",171);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",171);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",171);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",176);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",176);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",176);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",176);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",176);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",176);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",176);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",181);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",181);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",181);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",181);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",181);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",181);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",181);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",186);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",186);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",186);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",186);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",186);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",186);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",186);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",191);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",191);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",191);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",191);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",191);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",191);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",191);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",196);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",196);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",196);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",196);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",196);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",196);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",196);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",201);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",201);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",201);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",201);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",201);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",201);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",201);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",206);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",206);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",206);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",206);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",206);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",206);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",206);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",211);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",211);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",211);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",211);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",211);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",211);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",211);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",216);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",216);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",216);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",216);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",216);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",216);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",216);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",221);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",221);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",221);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",221);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",221);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",221);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",221);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",226);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",226);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",226);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",226);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",226);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",226);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",226);
insert into services(duration,name,agency_id) values(5,"Autorizare Ateliere Service",231);
insert into services(duration,name,agency_id) values(10,"Autorizare ateliere aplicare folie",231);
insert into services(duration,name,agency_id) values(15,"Autorizare Ateliere GPL",231);
insert into services(duration,name,agency_id) values(20,"Autorizare Ateliere TLV",231);
insert into services(duration,name,agency_id) values(30,"Autorizare Staţii ITP",231);
insert into services(duration,name,agency_id) values(60,"Ceritificare produse",231);
insert into services(duration,name,agency_id) values(5,"Acordarea numărului naţional de registru",231);
insert into services(duration,name,agency_id) values(30,"taxa auto",4);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",4);
insert into services(duration,name,agency_id) values(30,"taxa auto",9);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",9);
insert into services(duration,name,agency_id) values(30,"taxa auto",14);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",14);
insert into services(duration,name,agency_id) values(30,"taxa auto",19);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",19);
insert into services(duration,name,agency_id) values(30,"taxa auto",24);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",24);
insert into services(duration,name,agency_id) values(30,"taxa auto",29);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",29);
insert into services(duration,name,agency_id) values(30,"taxa auto",34);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",34);
insert into services(duration,name,agency_id) values(30,"taxa auto",39);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",39);
insert into services(duration,name,agency_id) values(30,"taxa auto",44);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",44);
insert into services(duration,name,agency_id) values(30,"taxa auto",49);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",49);
insert into services(duration,name,agency_id) values(30,"taxa auto",54);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",54);
insert into services(duration,name,agency_id) values(30,"taxa auto",59);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",59);
insert into services(duration,name,agency_id) values(30,"taxa auto",64);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",64);
insert into services(duration,name,agency_id) values(30,"taxa auto",69);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",69);
insert into services(duration,name,agency_id) values(30,"taxa auto",74);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",74);
insert into services(duration,name,agency_id) values(30,"taxa auto",79);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",79);
insert into services(duration,name,agency_id) values(30,"taxa auto",84);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",84);
insert into services(duration,name,agency_id) values(30,"taxa auto",89);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",89);
insert into services(duration,name,agency_id) values(30,"taxa auto",94);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",94);
insert into services(duration,name,agency_id) values(30,"taxa auto",99);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",99);
insert into services(duration,name,agency_id) values(30,"taxa auto",104);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",104);
insert into services(duration,name,agency_id) values(30,"taxa auto",109);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",109);
insert into services(duration,name,agency_id) values(30,"taxa auto",114);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",114);
insert into services(duration,name,agency_id) values(30,"taxa auto",119);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",119);
insert into services(duration,name,agency_id) values(30,"taxa auto",124);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",124);
insert into services(duration,name,agency_id) values(30,"taxa auto",129);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",129);
insert into services(duration,name,agency_id) values(30,"taxa auto",134);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",134);
insert into services(duration,name,agency_id) values(30,"taxa auto",139);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",139);
insert into services(duration,name,agency_id) values(30,"taxa auto",144);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",144);
insert into services(duration,name,agency_id) values(30,"taxa auto",149);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",149);
insert into services(duration,name,agency_id) values(30,"taxa auto",154);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",154);
insert into services(duration,name,agency_id) values(30,"taxa auto",159);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",159);
insert into services(duration,name,agency_id) values(30,"taxa auto",164);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",164);
insert into services(duration,name,agency_id) values(30,"taxa auto",169);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",169);
insert into services(duration,name,agency_id) values(30,"taxa auto",174);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",174);
insert into services(duration,name,agency_id) values(30,"taxa auto",179);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",179);
insert into services(duration,name,agency_id) values(30,"taxa auto",184);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",184);
insert into services(duration,name,agency_id) values(30,"taxa auto",189);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",189);
insert into services(duration,name,agency_id) values(30,"taxa auto",194);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",194);
insert into services(duration,name,agency_id) values(30,"taxa auto",199);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",199);
insert into services(duration,name,agency_id) values(30,"taxa auto",204);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",204);
insert into services(duration,name,agency_id) values(30,"taxa auto",209);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",209);
insert into services(duration,name,agency_id) values(30,"taxa auto",214);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",214);
insert into services(duration,name,agency_id) values(30,"taxa auto",219);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",219);
insert into services(duration,name,agency_id) values(30,"taxa auto",224);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",224);
insert into services(duration,name,agency_id) values(30,"taxa auto",229);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",229);
insert into services(duration,name,agency_id) values(30,"taxa auto",234);
insert into services(duration,name,agency_id) values(60,"taxa pasaport",234);
